### ISSUE TITLE
qsstv_X.X.conf is kept in confusingly named ~/.config/ON4QZ

### ISSUE THREAD

**Issue by hspil** [ON4QZ/QSSTV#7]
Perhaps rename default config file directory to ~/.config/qsstv

**Comment by dl8dtl** [comment]
Well, the two-stage config hierarchy is probably a kind of convention, to avoid a completely flat (and crowded) directory.
So it's "organization"/"application", and Qt automatically handles that.

The setup is:
(`appglobal.cpp`)
```
const QString CONFIGVERSION = "9.0";
//…
const QString ORGANIZATION = "ON4QZ";
const QString APPLICATION  = ("qsstv_" +CONFIGVERSION);
```
(`main.cpp`)
```
  QCoreApplication::setOrganizationName(ORGANIZATION);
  QCoreApplication::setApplicationName(APPLICATION);
```

Thus, in order to change this, we'd neet to set the ORGANIZATION also to "QSSTV", but then we have "QSSTV/qsstv_X.X".

**Comment by dl8dtl** [comment]
When changing it, some kind of "oh, there's an old config directory present, migrate the data" would be needed, thus making the entire handling a lot more complicated – the current handling is transparently done by Qt. I guess that alone is a good reason to not touch it …
